/*
Copyright 2025 The Knative Authors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

	http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	context "context"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
	operatorv1alpha1 "knative.dev/eventmesh-operator/pkg/apis/operator/v1alpha1"
	scheme "knative.dev/eventmesh-operator/pkg/client/clientset/versioned/scheme"
)

// EventMeshesGetter has a method to return a EventMeshInterface.
// A group's client should implement this interface.
type EventMeshesGetter interface {
	EventMeshes(namespace string) EventMeshInterface
}

// EventMeshInterface has methods to work with EventMesh resources.
type EventMeshInterface interface {
	Create(ctx context.Context, eventMesh *operatorv1alpha1.EventMesh, opts v1.CreateOptions) (*operatorv1alpha1.EventMesh, error)
	Update(ctx context.Context, eventMesh *operatorv1alpha1.EventMesh, opts v1.UpdateOptions) (*operatorv1alpha1.EventMesh, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, eventMesh *operatorv1alpha1.EventMesh, opts v1.UpdateOptions) (*operatorv1alpha1.EventMesh, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*operatorv1alpha1.EventMesh, error)
	List(ctx context.Context, opts v1.ListOptions) (*operatorv1alpha1.EventMeshList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *operatorv1alpha1.EventMesh, err error)
	EventMeshExpansion
}

// eventMeshes implements EventMeshInterface
type eventMeshes struct {
	*gentype.ClientWithList[*operatorv1alpha1.EventMesh, *operatorv1alpha1.EventMeshList]
}

// newEventMeshes returns a EventMeshes
func newEventMeshes(c *OperatorV1alpha1Client, namespace string) *eventMeshes {
	return &eventMeshes{
		gentype.NewClientWithList[*operatorv1alpha1.EventMesh, *operatorv1alpha1.EventMeshList](
			"eventmeshes",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *operatorv1alpha1.EventMesh { return &operatorv1alpha1.EventMesh{} },
			func() *operatorv1alpha1.EventMeshList { return &operatorv1alpha1.EventMeshList{} },
		),
	}
}
